name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        make build
        mkdir -p dist
        mv bin/wpress-extract-* dist/

    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: dist/
        retention-days: 5

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: binaries

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        files: |
          wpress-extract-*
